In [1]:
import os
import geopandas as gpd

In [2]:
folder_path = '/green-projects/project-urban_colocation_intelligence/workspace/share/data/boundary/London_LSOA_2021'
data_folder_path = os.path.join(folder_path, 'origdata', 'LB_shp')

# **City of London**

In [3]:
file_path = os.path.join(data_folder_path, 'City of London.shp')
city_of_london = gpd.read_file(file_path)
city_of_london

,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,geometry
0,E01000003,City of London 001C,E02000001,City of London 001,E09000001,City of London,"POLYGON ((532153.703 182165.155, 532158.25 182..."
1,E01000005,City of London 001E,E02000001,City of London 001,E09000001,City of London,"POLYGON ((533619.062 181402.364, 533639.868 18..."
2,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,"POLYGON ((532151.538 181867.433, 532152.5 1818..."
3,E01000002,City of London 001B,E02000001,City of London 001,E09000001,City of London,"POLYGON ((532634.497 181926.016, 532632.048 18..."
4,E01032740,City of London 001G,E02000001,City of London 001,E09000001,City of London,"POLYGON ((532020.161 181805.675, 532021.188 18..."
5,E01032739,City of London 001F,E02000001,City of London 001,E09000001,City of London,"POLYGON ((533376.156 181863.888, 533372.156 18..."

In [4]:
output_path = os.path.join(folder_path, 'output', 'city_of_london.geojson')
city_of_london.to_file(output_path, driver='GeoJSON')
print(f"Successfully exported to {output_path}")

Successfully exported to /green-projects/project-urban_colocation_intelligence/workspace/share/data/boundary/London_LSOA_2021/output/city_of_london.geojson

# **Canary Wharf**

In [5]:
file_path = os.path.join(data_folder_path, 'Tower Hamlets.shp')
tower_hamlets = gpd.read_file(file_path)
tower_hamlets

,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,geometry
0,E01004198,Tower Hamlets 002B,E02000865,Tower Hamlets 002,E09000030,Tower Hamlets,"POLYGON ((535056.623 183297.891, 535057.573 18..."
1,E01004199,Tower Hamlets 002C,E02000865,Tower Hamlets 002,E09000030,Tower Hamlets,"POLYGON ((534827.67 183222.599, 534828.862 183..."
2,E01004200,Tower Hamlets 005A,E02000868,Tower Hamlets 005,E09000030,Tower Hamlets,"POLYGON ((534671 183256, 534673.363 183250.096..."
3,E01004202,Tower Hamlets 005B,E02000868,Tower Hamlets 005,E09000030,Tower Hamlets,"POLYGON ((534717.138 183472.093, 534720 183472..."
4,E01004204,Tower Hamlets 005D,E02000868,Tower Hamlets 005,E09000030,Tower Hamlets,"POLYGON ((534272.051 183171.596, 534276.976 18..."
...,...,...,...,...,...,...,...
164,E01035702,Tower Hamlets 034C,E02007112,Tower Hamlets 034,E09000030,Tower Hamlets,"POLYGON ((539048 181080.547, 539044.875 181067..."
165,E01004234,Tower Hamlets 003E,E02000866,Tower Hamlets 003,E09000030,Tower Hamlets,"POLYGON ((536078.125 183947.719, 536086.25 183..."
166,E01004223,Tower Hamlets 001B,E02000864,Tower Hamlets 001,E09000030,Tower Hamlets,"POLYGON ((536766.888 184460.814, 536774.268 18..."
167,E01004277,Tower Hamlets 033A,E02006854,Tower Hamlets 033,E09000030,Tower Hamlets,"POLYGON ((537424.563 180688.516, 537424.938 18..."
168,E01032764,Tower Hamlets 004E,E02000867,Tower Hamlets 004,E09000030,Tower Hamlets,"POLYGON ((537466.814 184044.25, 537452.785 184..."

**Canary Wharf's `lsoa21cd`**: E01004277, E01032771, E01032780, E01032782

In [6]:
canary_wharf_lsoa = ['E01004277', 'E01032771', 'E01032780', 'E01032782']
canary_wharf = tower_hamlets[tower_hamlets['lsoa21cd'].isin(canary_wharf_lsoa)]
canary_wharf

,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,geometry
106,E01032782,Tower Hamlets 033D,E02006854,Tower Hamlets 033,E09000030,Tower Hamlets,"POLYGON ((537382.374 179897.795, 537376.846 17..."
159,E01032771,Tower Hamlets 033B,E02006854,Tower Hamlets 033,E09000030,Tower Hamlets,"POLYGON ((537462.897 180356.184, 537500 180350..."
160,E01032780,Tower Hamlets 035D,E02007113,Tower Hamlets 035,E09000030,Tower Hamlets,"POLYGON ((538460.798 180649.4, 538476.241 1806..."
167,E01004277,Tower Hamlets 033A,E02006854,Tower Hamlets 033,E09000030,Tower Hamlets,"POLYGON ((537424.563 180688.516, 537424.938 18..."

In [7]:
output_path = os.path.join(folder_path, 'output', 'canary_wharf.geojson')
canary_wharf.to_file(output_path, driver='GeoJSON')
print(f"Successfully exported to {output_path}")

Successfully exported to /green-projects/project-urban_colocation_intelligence/workspace/share/data/boundary/London_LSOA_2021/output/canary_wharf.geojson